apiVersion: v1
description: "Kubernetes resources for csm-config"
name: "csm-config"
home: "scms/csm-config"
version: 1.1.4
keywords:
  - csm
  - cfs
sources:
  - "https://stash.us.cray.com/projects/SCMS/repos/csm-config/browse"
maintainers:
  - name: jsl
    email: joel.landsteiner@hpe.com
