apiVersion: v1
description: "Kubernetes resources for csm-config"
name: "csm-config"
home: "scms/csm-config"
version: @product_version@
keywords:
  - csm
  - cfs
sources:
  - "https://github.com/Cray-HPE/csm-config"
maintainers:
  - name: jsl
    email: joel.landsteiner@hpe.com
