#!/usr/bin/env ansible-playbook
#
# MIT License
#
# (C) Copyright 2021-2024 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# stock SLES application/compute node playbook

---
- hosts: Application:Compute:&cfs_image
  gather_facts: false
  remote_user: root
  tasks:
    - name: Check for GCP environment
      uri:
        url: http://metadata.google.internal
        timeout: 20
        return_content: yes
      register: google_metadata
      changed_when: no
      check_mode: no
      failed_when: no

    - name: Set GCP fact
      set_fact:
        gcp_environment: true
      when: google_metadata.status == 200

- hosts: Application:Compute
  gather_subset:
    - '!all'
    - '!min'
    - distribution
  any_errors_fatal: true
  remote_user: root
  roles:
    - role: csm.ca_cert
    - role: csm.password
    - role: csm.ssh_keys
    - role: csm.cn.exclude-module

- hosts: Application:Compute:&cfs_image
  gather_subset:
    - '!all'
    - '!min'
    - distribution
  any_errors_fatal: true
  remote_user: root
  roles:
    - role: csm.cn.limits
    - role: csm.cn.ntp
    - role: csm.cn.localtime
    - role: csm.cn.dns-resolver
    - role: csm.cn.netif
    - role: csm.cn.rsyslog
    - role: csm.rebuild-initrd
