#!/usr/bin/env ansible-playbook
# Copyright 2021 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# (MIT License)

# NCN Worker Nodes Play
- hosts: Management_Worker
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root
  vars_files:
    - vars/csm_repos.yml
    - vars/csm_packages.yml

  roles:
    # Allow trust of CSM generated keys for elective passwordless SSH;
    # Enables both passwordless ssh from, and to, all nodes.
    - role: trust-csm-ssh-keys
    - role: passwordless-ssh

    # Install CSM repositories and packages
    - role: csm.packages

    # Set the root password from the value stored in cray-vault
    - role: csm.password
      vars:
        password_username: 'root'

    # Distribute SSH keys for the root user
    - role: csm.ssh_keys
      vars:
        ssh_keys_username: 'root'

