#!/usr/bin/env ansible-playbook
#
# MIT License
#
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Deprecation Notice: These top level playbooks are replaced by ncn_nodes.yml
---
- name: setup cfs_image host group
  gather_facts: false
  hosts: all
  tasks:
    - name: Add image customization hosts to the cfs_image host group.
      add_host:
        name: '{{ inventory_hostname }}'
        groups: cfs_image
      when: cray_cfs_image

- hosts: all
  gather_facts: no
  tasks:
    - name: DEPRECATION NOTICE
      debug:
        msg: "This playbook is marked for deprecation, please use the unified ncn_nodes.yml playbook instead."
      run_once: true
      delegate_to: localhost

# NCN Master Nodes Plays, and plays intended for the Management Master Node and associated image
# Does not include images
- hosts: Management_Master!cfs_image
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root
  vars_files:
    - vars/csm_repos.yml
    - vars/csm_packages.yml
  roles:
    - role: csm.ncn.sysctl
      vars:
        sysctl_set: true
    - role: trust-csm-ssh-keys
    - role: csm.ca_cert
    - role: csm.packages
      vars:
        packages: "{{ common_csm_sles_packages + common_mgmt_ncn_csm_sles_packages + k8s_mgmt_ncn_csm_sles_packages }}"
      when: ansible_distribution_file_variety == "SUSE"
    - role: passwordless-ssh
    - role: csm.password
      vars:
        password_username: 'root'
    - role: csm.ssh_keys
      vars:
        ssh_keys_username: 'root'

# NCN Master Nodes Plays, and plays intended for the Management Master Node and associated image
# Includes images
- hosts: Management_Master:&cfs_image
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root
  vars_files:
    - vars/csm_repos.yml
    - vars/csm_packages.yml
  roles:
    - role: csm.ncn.sysctl
      vars:
        sysctl_set: false
    - role: trust-csm-ssh-keys
    - role: csm.ca_cert
    - role: csm.packages
      vars:
        packages: "{{ common_csm_sles_packages + common_mgmt_ncn_csm_sles_packages + k8s_mgmt_ncn_csm_sles_packages }}"
      when: ansible_distribution_file_variety == "SUSE"
    - role: passwordless-ssh
    - role: csm.password
      vars:
        password_username: 'root'
    - role: csm.ssh_keys
      vars:
        ssh_keys_username: 'root'