#!/usr/bin/env ansible-playbook
# Copyright 2020 Hewlett Packard Enterprise Development LP
# Top-level site.yml for CSM Deployed Environments (NCNs, except for UANs)
- hosts: all
  gather_facts: yes
  any_errors_fatal: true
  remote_user: root
  roles:
    # Allow trust of CSM generated keys for elective passwordless SSH;
    # Enables both passwordless ssh from, and to, all nodes.
    - role: trust-csm-ssh-keys
    - role: passwordless-ssh

