#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: insert-labels-topology-constraints
  annotations:
    policies.kyverno.io/title: Add Pod topology constraints
    policies.kyverno.io/subject: Deployment
    policies.kyverno.io/minversion: 1.6.0
spec:
  rules:
    - name: insert-rack-res-label
      match:
        any:
        - resources:
            names:
            - cray-dns-powerdns
            - coredns
            - sealed-secrets
            - cray-ceph-csi-cephfs-provisioner
            - cray-ceph-csi-rbd-provisioner
            - cray-activemq-artemis-operator-controller-manager
            - cray-dvs-mqtt-ss
            - cray-hmnfd-bitnami-etcd
            - cray-hmnfd
            - cray-hbtd
            - cray-hbtd-bitnami-etcd
            - hpe-slingshot-jackaloped
            - hpe-slingshot-ogopogod
            - slingshot-fabric-manager
            - hpe-slingshot-vnid
            - cray-console-node
            - cray-powerdns-manager
            - cray-dns-powerdns-manager
            - cray-dhcp-kea
            - cray-sls
            - cray-keycloak
            - kiali
            - istiod
            - istio-ingressgateway
            - istio-ingressgateway-hmn
            - istio-ingressgateway-customer-user
            - istio-ingressgateway-customer-admin
            - istio-operator
            - gitea-vcs
            - cfs-ara
            - cfs-hwsync-agent
            - cfs-trust
            - cray-cfs-api
            - cray-cfs-api-db
            - cray-cfs-operator
            - cray-bos
            - cray-bos-db
            - nexus
            - cray-certmanager-cert-manager
            - cray-certmanager-cert-manager-cainjector
            - cray-certmanager-cert-manager-webhook
            - cray-bss
            - cray-bss-bitnami-etcd
            - cray-smd
            - cray-tftp
            - cray-ipxe-aarch64
            - cray-ipxe-x86-64
            - cray-sts
            - cray-vault-configurer
            - cray-vault-operator
            - cray-vault
            - spire-server
            - kyverno-background-controller
            - kyverno-cleanup-controller
            - kyverno-reports-controller
            - cray-power-control
            - cray-power-control-bitnami-etcd
            - cray-capmc
            - cray-tftp
            - cray-spire-server
            - slurm-operator
            - slurmctld
            - slurmctld-backup
            - slurmdbd
            - slurmdbd-backup
            - slurmdb-haproxy
            - slurmdb-pxc
            - pbs
            - pbs-comm
            - cray-cfs-batcher
            - cilium-operator
            - kyverno-admission-controller            
            kinds:
            - Deployment
            - StatefulSet
      # Mutates the Deployment resource to add fields.
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                labels:
                  rrflag: "rr-{{ request.object.metadata.name }}"
              spec:
                # Add the `topologySpreadConstraint`if not already specified.
                +(topologySpreadConstraints):
                - topologyKey: topology.kubernetes.io/zone
                  whenUnsatisfiable: ScheduleAnyway
                  maxSkew: 1
                  labelSelector:
                    matchLabels:
                      rrflag: "rr-{{ request.object.metadata.name }}"
