#
# MIT License
#
# (C) Copyright 2021-2023 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Tasks for the csm.ssh_keys role
- name: Get vault token
  no_log: true
  uri:
    url: "{{ ssh_keys_vault_url }}/v1/auth/kubernetes/login"
    method: POST
    body:
      jwt: "{{ lookup('file', ssh_keys_vault_jwt_file) }}"
      role: "{{ lookup('file', ssh_keys_vault_role_file) }}"
    body_format: json
  register: vault_login
  delegate_to: localhost
  run_once: true

- name: Retrieve the ssh private key
  block:
    - name: Lookup the private key value in Vault
      no_log: true
      run_once: true
      delegate_to: localhost
      set_fact:
        ssh_priv_key: "{{ lookup('hashi_vault',
                      'secret=' + ssh_keys_user_private_key_secret_prefix + ssh_keys_username + ':' + ssh_keys_user_private_key_key +
                      ' token=' + vault_login.json.auth.client_token +
                      ' url=' + ssh_keys_vault_url) }}"
  rescue:
    - name: set the value if no private key was found
      set_fact:
        ssh_priv_key: ''

- name: Retrieve the ssh public key
  block:
    - name: Lookup the public key value in Vault
      run_once: true
      delegate_to: localhost
      set_fact:
        ssh_pub_key: "{{ lookup('hashi_vault',
                     'secret=' + ssh_keys_user_public_key_secret_prefix + ssh_keys_username + ':' + ssh_keys_user_public_key_key +
                     ' token=' + vault_login.json.auth.client_token +
                     ' url=' + ssh_keys_vault_url) }}"
  rescue:
    - name: set the value if no public key was found
      set_fact:
        ssh_pub_key: ''

- name: Determine if play will go on
  debug: msg="Neither a private or public key exist in Vault for the {{ ssh_keys_username }} user. Exiting without error."
  when: ssh_pub_key == '' and ssh_priv_key == ''

- name: End play if neither key exists in Vault
  meta: end_play
  when: ssh_pub_key == '' and ssh_priv_key == ''

- name: Ensure the user exists
  user:
    name: "{{ ssh_keys_username }}"
    state: present
  register: user_registered

- name: Add the public key to the authorized keys file
  authorized_key:
    state: present
    user: "{{ ssh_keys_username }}"
    key: "{{ ssh_pub_key }}"
  when: ssh_pub_key != ''

# A newline is appended to the file contents for both files. If the file does not end with a newline, SSH considers
# it to be in an invalid format. Additional superfluous newlines do not cause a problem. Therefore, we append a newline
# to both SSH key files, because:
# 1. There is no reason an administrator would want to populate their SSH key files with an invalid format, and
# 2. We have seen cases where users accidentally omit the trailing newline when putting these values in Vault.

- name: Copy the public key
  copy:
    content: "{{ ssh_pub_key }}\n"
    dest: "{{ user_registered.home }}/.ssh/id_{{ ssh_keys_keytype }}.pub"
    mode: 0644
  become: true
  become_user: "{{ ssh_keys_username }}"
  when: ssh_pub_key != ''

- name: Copy the private key
  no_log: true
  copy:
    content: "{{ ssh_priv_key }}\n"
    dest: "{{ user_registered.home }}/.ssh/id_{{ ssh_keys_keytype }}"
    mode: 0600
  become: true
  become_user: "{{ ssh_keys_username }}"
  when: ssh_priv_key != ''

