#
# MIT License
#
# (C) Copyright 2025 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
---
# Check for Rack Resiliency(RR) feature enablement/ disablement
# with site-init secret flag
- name: Check Rack Resiliency Enablement
  script: check_rr_enablement.py
  args:
    executable: python3
  register: rr_enablement_flag
  delegate_to: "{{ play_hosts | first }}"
  run_once: true
  changed_when: rr_enablement_flag.rc == 0

# If RR feature is disabled, stop enabling RR
- name: Stop enabling Rack Resiliency if it is disabled in site-init
  run_once: true
  ansible.builtin.fail:
    msg: "Rack Resiliency(RR) is currently disabled, Exiting RR enablement."
  when: "'false' in rr_enablement_flag.stdout"
