name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - master
      - release/**
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/.github/.github/workflows/charts-lint-test-scan.yml@main
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      scan-images: false
      scan-charts: false
    secrets:
      snyk-token: ${{ secrets.SNYK_TOKEN }}