#
# MIT License
#
# (C) Copyright 2022 Hewlett Packard Enterprise Development LP
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
name: Gitflow Merge Back
on:
  pull_request:
    types: [ closed ]
    branches: [ master ]

jobs:
  merge-to-develop:
    # this job will only run if the PR has been merged, not just closed
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - name: Create the gitflow mergeback PR
        uses: Cray-HPE/.github/actions/csm-gitflow-mergeback@v1-csm-gitflow-mergeback
        id: create-pr
        with:
          source-branch: master
          base-branch: develop
          automerge: true
          app-key: ${{ secrets.CSM_GITFLOW_MERGEBACK_BOT_APP_KEY }}
          app-id: ${{ secrets.CSM_GITFLOW_MERGEBACK_BOT_APP_ID }}

      - name: Generated Pull Request Info
        shell: bash
        run: |
          echo "Pull Request Number - ${{ steps.create-pr.outputs.pr-number }}"
          echo "Pull Request URL - ${{ steps.create-pr.outputs.pr-url }}"
